### ISSUE TITLE
i need sample app for ionic 3

### ISSUE THREAD

**Issue by benson-jala** [viking2917/ionic-epub-reader#3]

**Comment by viking2917** [comment]
Hi @benson-jala unfortunately I am not familiar with Ionic 3 (which uses Angular, not AngularJS, they are pretty different) -  I only use Ionic / Angular 1. All the reader logic is in the angularEpubReader.js file, and the epubreader directive. That would have to be converted to whatever the equivalent is in ionic 3...

**Comment by benson-jala** [comment]
> Hi @benson-jala unfortunately I am not familiar with Ionic 3 (which uses Angular, not AngularJS, they are pretty different) - I only use Ionic / Angular 1. All the reader logic is in the angularEpubReader.js file, and the epubreader directive. That would have to be converted to whatever the equivalent is in ionic 3...

Thanks viking, are you using local storage or storage db for bookmark and notes?

**Comment by viking2917** [comment]
Hi @benson-jala sorry I missed your question. The directive will work either way, there is an argument passed to the directive as to whether to store the bookmarks in local storage (which is the default). See this file: https://github.com/viking2917/ionic-epub-reader/blob/master/www/templates/tab-reader.html and the directions in the Readme. 

I use a variant of this code for my social reading app [Bookship](https://www.bookshipapp.com). In that app I do not store in local storage but rather in my back end database, so that they can be shared across devices and survive the app being re-installed (which wipes the local storage I believe).

As noted in the Readme, there are lifecycle events which emit this information. If you want to store in an external database, you can watch those events in your app and then store the data as appropriate.

**Comment by benson-jala** [comment]
Thanks Viking

**Comment by viking2917** [comment]
Going to close this, I am not familiar with Ionic 3 so unfortunately cannot provide a sample app without more time than I can commit to it...thanks!
